#!/bin/bash

##############################################
# Cleans all test results data
#
# Data generated by test runs can become huge
# this script gets rid of all previous results.
#
##############################################

# Exit on errors.
set -e

# Dependencies.
. ./lib/lib.sh

# Get config.
load_properties "defaults.properties"
load_properties "webserver_config.properties"

delete_files "runs/*.php"
delete_files "runs_samples/*.jtl"
delete_files "runs_outputs/*.output"
delete_files "logs/*.log"

# Also images cache.
sudo delete_files "cache"

# Also backups.
sudo delete_files "$backupsdir/*"

# Delete compare files.
if [ -f "moodle/site_data.properties" ]; then
    delete_files "moodle/site_data.properties" 1
fi

if [ -f "test_files.properties" ]; then
    delete_files "test_files.properties" 1
fi

outputinfo="
#######################################################################
Runs results and backups deleted successfully.
"
echo "$outputinfo"
exit 0
