#!/bin/bash

##############################################
# Cleans all test results data
#
# Data generated by test runs can become huge
# this script gets rid of all previous results.
#
##############################################

# Exit on errors.
#set -e

# Dependencies.
. ./lib/lib.sh

# Get config.
load_properties "defaults.properties"
load_properties "webserver_config.properties"

rm runs/*.php -rf
rm runs_samples/*.jtl -rf
rm runs_outputs/*.output -rf
rm logs/*.log -rf

# Also images cache.
sudo rm cache -rf

# Also backups.
sudo rm $backupsdir/* -rf

# Delete compare files.
if [ -f "moodle/site_data.properties" ]; then
    rm moodle/site_data.properties -f
fi

if [ -f "test_files.properties" ]; then
    rm test_files.properties -f
fi

outputinfo="
#######################################################################
Runs results and backups deleted successfully.
"
echo "$outputinfo"
exit 0
